[workspace]
resolver = "2"
members = [
    "drivers/dacx578", 
    "drivers/ina233", 
    "drivers/sn74xx165", 
    "firmware"
]

default-members = ["firmware"]

exclude = ["pcbs/amp-brd-v4/refs/mcp19061_calc"]

[workspace.dependencies]
ina233 = { path = "drivers/ina233", default-features = false }
dacx578 = { path = "drivers/dacx578", default-features = false }
sn74xx165 = { path = "drivers/sn74xx165", default-features = false}
kmdparse = { version = "0.0.3" }
uom = { version = "0.38", default-features = false }

[profile.release]
debug = 0
lto = true
opt-level = 'z'

[profile.release.package."*"] # +
opt-level = "z" # +

[profile.dev]
debug = 2
lto = true
opt-level = "z"
