[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip RP2040 --protocol swd"
# runner = "probe-rs run --chip RP235x --protocol swd"
runner = "probe-rp-usb run --family rp2xxx-absolute"
# runner = "elf2uf2-rs -d"
# runner = "picotool load -u -v -x -t elf"

[build]
target = "thumbv8m.main-none-eabihf" # RP2350x

[target.thumbv8m.main-none-eabihf]
rustflags = [
    "-C",
    "link-arg=--nmagic",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "debug"
EMBASSY_USB_MAX_INTERFACE_COUNT = "10" # 0 -> Picoboot interface, 2 -> Configuration interface, 4 -> Report interface, 6 -> Logger interface, 8 -> CDC Defmt interface